# These are supported funding model platforms

custom: ['https://paypal.me/voldikss', 'https://user-images.githubusercontent.com/20282795/78157412-82eec000-7472-11ea-88d9-1fe81ceed50b.jpeg']
patreon: voldikss
